server:
  port: 8018
  servlet:
    context-path: /f-test

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:8306/f_permissions_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: f_test
      password: f_test
      filters: stat
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
  ################### 文件上传大小配置 ##########################
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB
  thymeleaf:
    check-template: false
    check-template-location: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 200
        max-wait: 10000
        max-idle: 150
        min-idle: 50
    expire: 3000
mybatis:
  permissions:
    column: org_code




