spring:
  profiles:
    active: @profileActive@
  application:
    name: feng-fund
  http:
    encoding:
      force: true
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

################# mybatis Configuration#######################################
mybatis:
  configuration:
    cache-enabled: false
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.f.demo.common.model.entity
################# pagehelper Configuration##################################
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true