package com.f.demo.module.cust.mapper;

import com.f.demo.common.model.entity.FCustomer;
import com.f.permissions.mybatis.DataPermissions;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_customer
     *
     * @mbggenerated
     */
    int insert(FCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_customer
     *
     * @mbggenerated
     */
    int insertSelective(FCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_customer
     *
     * @mbggenerated
     */
    FCustomer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FCustomer record);

    @DataPermissions("f_customer:org_code:org_start")
    List<FCustomer> listCust();

    List<FCustomer> listAllCust();
}